#' cldata
#'
#' cldata generates a summary dataframe based on individual cowlog csv observations. Additionaly it generates a list of zones dientified in the observations.
#' @param pathtofile path to folder hosting individual csv's generated by cowlog
#' @param outputdataname string of desired name for output summary dataframe of cowlog observations
#' @param outputzonename string of desired name for output list of zones identified in the cowlog observations
#' @param factor must be listed as either TRUE or FALSE, if true, one categorical factor is incorporated into the resulting summary dataframe
#' @param factorindex (used if factor = TRUE) index in cowlog individual csv's filename (separted by "_") that the factor of interest is located
#' @param factorname (used if factor = TRUE) string desired name for output column in summary dataframe referring to the factor of interest
#' @keywords cowlog
#' @keywords dataframe
#' @export
#' @examples
#' cldata(pathtofile = "C:/Users/example_files", outputdataname = "dataframe_round", outputzonename = "list_of_zones", factor = TRUE, factorindex = 3, factorname = "round")

cldata <- function(pathtofile, outputdataname, outputzonename, factor, factorindex,factorname){
  file_list<-list.files(path = pathtofile, pattern = "*.csv")
  all_codes<-"END"
  i<-1
  for (i in 1:length(file_list)){
    file<-read.csv(paste(pathtofile, file_list[i], sep= "/"))
    zones<-as.vector(unique(file$code))
    all_codes<-c(all_codes, zones)}

  unique_codes<-unique(all_codes)
  unique_codes<-unique_codes[unique_codes!= "END"]
  assign(outputzonename, unique_codes, envir=.GlobalEnv)

  file_name<-vector(length = length(file_list))
  data<-as.data.frame(file_name)
  data$file_name<-file_list


  if(factor == TRUE){
    data[factorname]<-  NA
    i<-1
    for (i in 1:nrow(data)){
      tempfactor<-file_list[i]
      tempfactor<-str_remove(tempfactor, ".csv")
      tempfactor<-strsplit(tempfactor, "_")[[1]][factorindex]
      data[i, factorname]<-tempfactor}}

  i<-1
  for (i in 1:length(unique_codes)){
    data[as.character(paste(unique_codes[i], "seconds", sep = "_"))]<-NA}


  j<-1
  for (j in 1:length(unique_codes)){
    tempname<-as.character(paste(unique_codes[j], "seconds", sep = "_"))
    i<-1
    for (i in 1:nrow(data)){
      file<-read.csv(paste(pathtofile, file_list[i], sep= "/"))
      file<-mutate(file, time_difference = -(time -lead(time)))
      vid_length <- file$time[nrow(file)] - file$time[1]
      data$vid_length[i]<-vid_length
      data[i,tempname]<-0
      if(file %>% filter(code == unique_codes[j]) %>% nrow() >0){
        data[i,tempname]<-file %>% filter(code == unique_codes[j]) %>% dplyr::select(time_difference) %>% sum()}}}

  i<-1
  for (i in 1:length(unique_codes)){
    data[as.character(paste(unique_codes[i], "prop", sep = "_"))]<-NA}
  j<-1
  for (j in 1:length(unique_codes)){
    tempnameprop<-as.character(paste(unique_codes[j], "prop", sep = "_"))
    tempnamesec<-as.character(paste(unique_codes[j], "seconds", sep = "_"))
    i<-1
    for (i in 1:nrow(data)){
      data[i,tempnameprop]<-(data[i,tempnamesec]/ data$vid_length[i])}}


  j<-1
  for (j in 1:length(unique_codes)){
    tempname<-as.character(paste(unique_codes[j], "entries", sep = "_"))
    i<-1
    for (i in 1:nrow(data)){
      file<-read.csv(paste(pathtofile, file_list[i], sep= "/"))
      data[i,tempname]<-file %>% filter(code == unique_codes[j]) %>% nrow()}}

  j<-1
  for (j in 1:length(unique_codes)){
    tempname<-as.character(paste(unique_codes[j], "first_entry_time", sep = "_"))
    i<-1
    for (i in 1:nrow(data)){
      file<-read.csv(paste(pathtofile, file_list[i], sep= "/"))
      data[i,tempname]<-NA
      if (file %>% filter(code == unique_codes[j]) %>% nrow()>0){
        data[i,tempname]<-file[file$code == unique_codes[j],"time"][1]}}}

  print(paste("NUMBER OF FILES:", length(file_list)))
  print(paste("NAME OF OUTPUT FILE:", outputdataname))
  print("AREAS:")
  print(as.matrix(unique_codes))
  assign(outputdataname, data, envir=.GlobalEnv)
}
