#' clflag
#'
#' clflag is designed to identify any cowlog csv observation sheets that do may host scorer input errors. It flags csv files that do not include an END entry, that have fewer than entries, and that report negative time differences between entries.
#' @param pathtofile path to folder hosting individual csv's generated by cowlog
#' @keywords cowlog
#' @keywords flag
#' @export
#' @examples
#' clflag(pathtofile = "C:/Users/example_files")

clflag <- function(pathtofile){
  file_list<-list.files(path = pathtofile, pattern = "*.csv")
  i<-1
  for (i in 1:length(file_list)){
    file<-read.csv(paste(pathtofile, file_list[i], sep= "/"))
    filename<-file_list[i]
    file<-as.data.frame(file)
    max<-nrow(file)
    if(file$code[max] != "END") {print(paste(filename, "WARNING: NO END"))}
    if(nrow(file) <5) {print(paste(filename, "WARNING: LESS THAN THREE ENTRIES"))}
    j<-1
    for (j in 1:nrow(file)){
      time_difference<-(as.numeric(file$time[j+1]))- (as.numeric(file$time[j]))
      if(is.na(time_difference) == FALSE & time_difference <0) {print(paste(filename, "WARNING: NEGATIVE TIME row", j ))}}}}
